
joints:
  forearm_roll:
    effort: 999.9
    gradual_startup_position: 0.0
    gradual_startup_time: 1.0
    antagonist: False
  wrist_pitch:
    effort: 0.0
    gradual_startup_position: 0.0
    gradual_startup_time: 1.0
    antagonist: True
