calibrated: 1
equilibrium:
    sign: -1
    signFlexor: 1
    signExtensor: 1
    nameFlexor: "wrist_flexor"
    nameExtensor: "wrist_extensor"
    servoRange: 5.4978
    servoOffset: 0.5
    loadLimit: 0.5  # Testing limitLoad method in equilibrium_model.py.
signEncoder: -1
signJoint: 1
name: "wrist_pitch"
nameEncoder: "wrist_encoder"
minAngle: -1.0
maxAngle: 1.0
maxAbsForwardError: 5.0
gains:
    P: 0.02
    I: 0.0
    D: 0.2
